#!/bin/bash

if [ "$#" -ne 0 ]; then
	java -cp .:"./jars/slf4j-api.jar:./jars/slf4j-simple.jar:./jars/jsoup.jar:./jars/jboss-client.jar" -Djava.util.logging.manager=java.util.logging.LogManager -Djava.util.logging.config.file=logging.properties "$1"
else
	echo "error: expected file name as an argument"
fi
